---
title: Neural net with nnet(), applied to density formula
author: Dan Kelley (member of AMORE group)
date: 2023-05-31
output: html_document
bibliography: amore.bib
runtime: shiny
---

# Choice of network solver

The `nnet()` function provides a good introduction to neural network analysis in
R, mainly because it is so easy to use.  But be aware that it has just a single
"hidden layer", which means that it cannot handle complicated tasks as well as
"convolutional" networks can, with their multiple hidden layers.  Another
limitation is that it uses `optim()` to do the optimization, which is likely to
be slower, and perhaps less effective, than more modern approaches.

Essentially, `nnet()` is a product of the early years of neural networks, before
Hinton and colleagues showed how back-propagation enables fast solution of
complex multilayered networks.

To learn more about back-propagation, see the seminal paper by
@rumelhart_learning_1986. More insights on the basic ideas, with a specific
focus on the Keras/TensorFlow approach, are provided in the highly-recommended
text by @chollet_deep_2022, which is especially insightful, since Keras was
written by Chollet. Note that the Keras/TensorFlow system was developed in a
language (Python) that allows functions to alter their arguments, and this
convention can lead to confusion for R users.

# Simulation

The following app shows how to use a neural network to represent the equation of
state (EOS) of seawater, $\sigma_0=\sigma_0(S_A, C_T)$.  The point is not to
replace the EOS, but rather to provide an example of oceanographic interest. Try
adjusting the sliders to learn how the accuracy of the solution varies with
network size and training-set size. The red dots are the training set, which is
regenerated randomly whenever either slider is altered, or when the "New
samples" button is clicked.  The "Reset sliders" button returns the sliders (but
not the random numbers) to the initial state.


```{r echo=FALSE}
suppressPackageStartupMessages(library(oce))
options(oceEOS="gsw")
library(nnet)

library(shiny)
ui <- fluidPage(titlePanel(title="", windowTitle="Neural Network (seawater density)"),
    style="text-indent:1em; background:#e6f3ff",
    sidebarPanel(
        sliderInput("nnode", value=30, min=10, max=100, step=1,
            label="Number of nodes"),
        sliderInput("ntrain", value=30, min=10, max=100, step=1,
            label="Number of training data"),
        actionButton("refresh", "New samples"),
        actionButton("reset", "Reset sliders")),
    mainPanel(plotOutput("plot")))

server <- function(input, output, session)
{
    output$plot <- renderPlot({
        input$refresh # cause a replot (with new training data) if 'refresh' is clicked
        # Show a Bedford Basin TS diagram (note the contours)
        data(ctd)
        plotTS(ctd, type="l", lwd=2, mar=c(3, 3, 1, 1))
        # Create a training set
        usr <- par("usr")
        SAt <- runif(input$ntrain, min=usr[1], max=usr[2])
        CTt <- runif(input$ntrain, min=usr[3], max=usr[4])
        # Show training set as red dots
        points(SAt, CTt, pch=20, cex=1.4, col=2)
        # Fit the neural network to the training set
        sigma0t <- gsw_sigma0(SAt, CTt)
        trainingSet <- list(SA=SAt, CT=CTt, sigma0=sigma0t)
        net <- nnet(sigma0 ~ SA+ CT, data=trainingSet, linout=TRUE, size=input$nnode)
        # Display results on a grid, as blue-dashed contours
        Ng <- 50
        SAg <- seq(usr[1], usr[2], length.out=Ng)
        CTg <- seq(usr[3], usr[4], length.out=Ng)
        g <- expand.grid(SA=SAg, CT=CTg)
        sigma0g <- predict(net, newdata=list(SA=g$SA, CT=g$CT))
        contour(SAg, CTg, matrix(sigma0g, nrow=Ng),
            level=seq(20, 30, 0.5),
            add=TRUE, col=4, lty="dashed", lwd=2, drawlabels=FALSE)
    }, pointsize=16)
    observeEvent(input$refresh,
        {
            message("REFRESH", file=stderr())
        })
    observeEvent(input$reset,
        {
            message("REFRESH", file=stderr())
            updateSliderInput(session, "nnode", value=30)
            updateSliderInput(session, "ntrain", value=30)
        })
}
shinyApp(ui=ui, server=server)
```

# References
