# install.packages("ncdf4")
library(ncdf4)
library(oce)
f <- "RSS_AMSR2_ocean_L3_3day_2024-06-11_v08.2.nc"
o <- nc_open(f)
SST <- ncvar_get(o, "SST")
lon <- ncvar_get(o, "lon")
lat <- ncvar_get(o, "lat")
cm <- colormap(zlim = c(-2, 35), col = oceColorsTurbo)
imagep(lon, lat, SST, asp = 1, colormap =cm)
xy <- locator(1)
i <- which.min(abs(xy$x - lon))
j <- which.min(abs(xy$y - lat))
mtext(sprintf("%.2fE %.2fN %.2f degC", lon[i], lat[j], SST[i, j]))
points(lon[i], lat[j])
