---
title: Notes from AMORE meeting 1
date: 2023-05-10
output: pdf_document
author: Dan Kelley (he, him)
---

**Summary**

About 15 individuals were present. In these notes, DEK is Dan Kelley and CGR is
Clark Richards, while "group" indicates group discussion^[Please note that
individuals in the AMORE group will not be named in meeting notes without
permission.].

*Topic 1.* Most of the time was spent with DEK talking about working with
github.com and, more generally, with git.  In this he was helped greatly by CGR.
After the meeting, DEK made a video (available at https:
//www.dropbox.com/s/xt5x9djdjpoglsw/amore_meeting_2_followup_2.mp4?dl=0) that is
much, much simpler method using the GitHub Desktop application.  This
application may be downloaded for free from github.com, and AMORE members
may find that it is ideal for initial work with git, because it greatly reduces
the need to remember git commands.

*Topic 2.* DEK showed code in sandbox/dek/emag2, which deals with earth magnetic
anomaly data.  DEK showed the R files one by one (noting that their names sort
to give the order of working).  It is not possible for others to follow the
steps because DEK did not include in the repo the large `.rda` file that is
required for this work.  That file could be put (temporarily) on Dropbox if
anyone wants ... just email DEK.  Note that DEK made some other magnetic declination
images after the meeting, and the source code for them is available in the
above-named directory.


**Plans**

In the next meeting, DEK will discuss regression, both linear and nonlinear.
The focus will be not just on the R functions that do these things, but also on
the theory behind them.  That theory is essential to do quite a lot of nonlinear
curve fitting, in particular.

**Resources**

After the meeting, DEK made a little video, illustrating git work and R-markdown format,
by writing the present document.  (There a few minutes of watching typing, with no words
spoken.  Oh, the drama of it all!)  The video is at
https://www.dropbox.com/s/ndw95kqh4m5ob6q/amore_meeting_2_followup.mp4?dl=0
