---
title: "Notes from AMORE meeting 8 (reading netcdf, plotting maps and sections, data wrangling)"
date: 2023-06-28
output: pdf_document
bibliography: amore.bib
author: Dan Kelley (he, him)
---

## Summary

Dan talked about the use of base-R functions `cut()`, `split()` and `lapply()`,
with a general introduction being followed by two examples relating to the
timeseries of atmospheric CO$_2$ concentration, i.e. the "Keeling Curve"
(see the engaging essay by @monroe_history_2013 for more on the history of this
dataset). This led to code included as `co2-year-average.R` in this directory.

More briefly, he pointed at code (file `co2-average-months.R` in this directory)
that takes more detailed CO2 data and breaks it down into years, and then into
months.

Dan also mentioned a stacking-plot example, showing the result but not the code.
That is included as the file `co2-stack-years.R` in the present directory.

## Plans

This was the last planned AMORE session for the summer of 2023.  That doesn't
means that members of the group are "on their own", though.  If the meetings
have been successful, participants will feel free to reach out to others in the
group if they need advice.

![Output from `co2-year-average.R`, the first part of which was discussed in the
meeting. The R file includes the computation of average time within each month
segment, and the drawing of the monthly average as a red line on top of the
monthly data (black).](co2-year-average.png)

![Output from `co2-average-months.R`, a snippet of which was discussed in the
meeting. The data were first split by year for subdivision into plot panels,
showing measurements with dots. Then each year was split into months to compute
monthly averages, shown here with lines.](co2-average-months.png)

![Output from `co2-stack-years.R`, which was shown in the meeting. Colour shifts
with each year, on a 9-year cycle. No offset is applied to subsequent years: the offsets
result from CO$_2$ increasing.](co2-stack-years.png)


# References
